# Generated by Django 5.2.17 on 2026-10-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Customer, created the first time a card is saved. Lets the customer reuse a card and lets staff charge it.', max_length=64),
        ),
    ]
