# Generated by Django 5.2.17 on 2026-08-12 17:49

import bookings.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, default=bookings.models.generate_reference, help_text='Customer-facing booking code.', max_length=16, unique=True)),
                ('trip_type', models.CharField(choices=[('transfer', 'Point-to-point transfer'), ('hourly', 'Hourly hire')], default='transfer', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_address', models.CharField(blank=True, max_length=255)),
                ('dropoff_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_at', models.DateTimeField(db_index=True)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=3, help_text='From the Distance Matrix API. Null for hourly hire.', max_digits=8, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, help_text='Booked hours, for hourly hire.', max_digits=5, null=True)),
                ('passenger_count', models.PositiveSmallIntegerField(default=1)),
                ('luggage_count', models.PositiveSmallIntegerField(default=0)),
                ('flight_number', models.CharField(blank=True, max_length=32)),
                ('pickup_sign', models.CharField(blank=True, help_text='Name shown on the placard.', max_length=120)),
                ('meet_and_greet', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Customer instructions.')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('surcharge_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('vehicle_name_snapshot', models.CharField(blank=True, help_text='Vehicle name as sold. Deliberate denormalisation: renaming the fleet must not rewrite history.', max_length=120)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('legacy_order_id', models.IntegerField(blank=True, db_index=True, help_text='`limousin_order.id`.', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Null for guest bookings. Deleting an account must not erase booking history.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(help_text='PROTECT: a vehicle with bookings can be deactivated, not deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.vehicle')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='bookings.driver')),
            ],
            options={
                'ordering': ['-pickup_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPriceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('base', 'Base fare'), ('band', 'Distance band'), ('surcharge', 'Surcharge'), ('meet_greet', 'Meet and greet'), ('minimum_adjustment', 'Minimum fare adjustment'), ('tax', 'Tax')], max_length=20)),
                ('label', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: adjustments may be negative.', max_digits=10)),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lines', to='bookings.booking')),
            ],
            options={
                'ordering': ['booking', 'ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'pickup_at'], name='bookings_bo_status_27ae41_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['pickup_at', 'status'], name='booking_dispatch_idx'),
        ),
    ]
