# Generated by Django 5.2.17 on 2026-08-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Contact address for a booking made without an account. Without it a guest can never receive their own confirmation.', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
