# Generated by Django 5.2.17 on 2026-10-08 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guest_email_booking_guest_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Login account for the driver app. Blank = no app access yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12),
        ),
    ]
