# Generated by Django 5.2.17 on 2026-10-09 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_driver_user_alter_booking_status'),
        ('pricing', '0003_cityroute_cityrouteprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city_route',
            field=models.ForeignKey(blank=True, help_text='Set when the fare came from a fixed city-to-city route.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='pricing.cityroute'),
        ),
    ]
