# Generated by Django 5.2.17 on 2026-08-13 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_booking_guest_email_booking_guest_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('booking_confirmation', 'Booking confirmation'), ('booking_cancelled', 'Booking cancelled'), ('driver_assigned', 'Driver assigned'), ('ops_new_booking', 'Operations: new booking'), ('pickup_reminder', 'Pickup reminder'), ('test', 'Test message'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('succeeded', models.BooleanField(db_index=True, default=False)),
                ('error', models.TextField(blank=True)),
                ('has_attachment', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='bookings.booking')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, help_text='e.g. mail.austinlimoshuttle.com', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('security', models.CharField(choices=[('tls', 'STARTTLS (usually port 587)'), ('ssl', 'SSL/TLS (usually port 465)'), ('none', 'None (not recommended)')], default='tls', max_length=4)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('_password', models.TextField(blank=True, db_column='password_encrypted', help_text='Encrypted at rest.', verbose_name='password')),
                ('from_name', models.CharField(blank=True, default='Austin Limo Shuttle', help_text='Display name on outgoing mail.', max_length=120)),
                ('from_email', models.EmailField(blank=True, help_text='Must be an address this mailbox is allowed to send as.', max_length=254)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('ops_notification_email', models.EmailField(blank=True, help_text='Where new-booking and cancellation alerts are sent.', max_length=254)),
                ('is_enabled', models.BooleanField(default=False, help_text='Turn off to stop all outgoing mail without deleting the settings.')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=15)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email settings',
                'verbose_name_plural': 'email settings',
            },
        ),
    ]
