# Generated by Django 5.2.17 on 2026-10-09 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_city_route'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('confirmation', 'Booking confirmation'), ('reminder', 'Pickup reminder'), ('test', 'Test'), ('other', 'Other')], default='other', max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('body', models.TextField(blank=True)),
                ('succeeded', models.BooleanField(default=False)),
                ('provider_sid', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='bookings.booking')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Turn off to stop all texts without deleting the credentials.')),
                ('account_sid', models.CharField(blank=True, help_text='Twilio Account SID (starts with AC).', max_length=64)),
                ('_auth_token', models.TextField(blank=True, db_column='auth_token_encrypted', help_text='Encrypted at rest.', verbose_name='auth token')),
                ('from_number', models.CharField(blank=True, help_text='The Twilio number texts are sent from, E.164 e.g. +15125550100.', max_length=20)),
                ('confirmation_enabled', models.BooleanField(default=True, help_text='Text the customer when a booking is confirmed.')),
                ('reminder_enabled', models.BooleanField(default=True, help_text='Text the customer a reminder before pickup.')),
                ('reminder_lead_hours', models.PositiveSmallIntegerField(default=24, help_text='How many hours before pickup to send the reminder (24 = a day ahead).')),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS settings',
                'verbose_name_plural': 'SMS settings',
            },
        ),
    ]
