# Generated by Django 5.2.17 on 2026-08-12 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('category', models.CharField(choices=[('gallery', 'Gallery'), ('partner', 'Partner logo')], default='gallery', help_text='Legacy used a misspelled `partrers` flag.', max_length=12)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_gallery_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('ops_notification_email', models.EmailField(blank=True, help_text='Where new-booking alerts are sent.', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5. Legacy stored this as free text.', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('legacy_testimonial_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL path. Changing this breaks search rankings — don't.", max_length=200, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('page_type', models.CharField(choices=[('home', 'Homepage'), ('service', 'Service landing page'), ('standard', 'Standard content page'), ('legal', 'Legal / policy page')], default='standard', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('menu_placement', models.CharField(choices=[('main', 'Main menu'), ('footer', 'Footer'), ('none', 'Not in any menu')], default='none', max_length=12)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('legacy_cms_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.page')),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('link_url', models.URLField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_banner_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('page', models.ForeignKey(blank=True, help_text='Leave empty for the homepage. Replaces the legacy H/P flag.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='content.page')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
