# Generated by Django 5.2.17 on 2026-10-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_api_key',
            field=models.CharField(blank=True, help_text="Google Maps key for address autocomplete and distance pricing. Leave blank to use the server's configured key.", max_length=120),
        ),
    ]
