# Generated by Django 5.2.17 on 2026-08-12 17:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackoutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "SXSW 2026".', max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('500.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_busy_date_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage applied to the fare. 0 disables tax lines.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('cancellation_window_hours', models.PositiveSmallIntegerField(default=1, help_text='Free cancellation up to this many hours before pickup. Legacy fleet copy advertised 1 hour.')),
                ('quote_ttl_minutes', models.PositiveSmallIntegerField(default=30, help_text='How long a fare quote stays valid.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pricing settings',
                'verbose_name_plural': 'pricing settings',
            },
        ),
        migrations.CreateModel(
            name='TimeSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_time', models.TimeField(help_text='Window opens after this time (exclusive).')),
                ('end_time', models.TimeField(help_text='Window closes at this time (exclusive).')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Uplift applied to the base fare, e.g. 20.00 for +20%.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('500.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('legacy_rate_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'time surcharge',
                'ordering': ['start_time'],
            },
        ),
    ]
