# Generated by Django 5.2.17 on 2026-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='amendment_window_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text="How many hours before pickup a customer may still change their booking's details online. 72 = 3 days, 24 = 1 day, 6 = 6 hours. After this they must contact the office."),
        ),
    ]
