# Generated by Django 5.2.17 on 2026-10-09 00:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('pricing', '0002_pricingsettings_amendment_window_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='e.g. Austin', max_length=120)),
                ('destination', models.CharField(help_text='e.g. San Antonio', max_length=120)),
                ('bidirectional', models.BooleanField(default=True, help_text='Also price the reverse direction at the same rate.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['origin', 'destination'],
                'constraints': [models.UniqueConstraint(fields=('origin', 'destination'), name='unique_city_route')],
            },
        ),
        migrations.CreateModel(
            name='CityRoutePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='All-in fare — no surcharges or tax are added on top.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricing.cityroute')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_route_prices', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['vehicle__display_order', 'vehicle__name'],
                'constraints': [models.UniqueConstraint(fields=('route', 'vehicle'), name='unique_route_vehicle_price')],
            },
        ),
    ]
