# Generated by Django 5.2.17 on 2026-10-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_cityroute_cityrouteprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingsettings',
            name='min_booking_lead_hours',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many hours before pickup a customer may still book online. 0 = no minimum, 2 = must book 2 hours ahead, 24 = a day ahead. Staff booking by phone in the back office are not limited.'),
        ),
    ]
