# Generated by Django 5.2.17 on 2026-08-12 17:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Business Class".', max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Marketing copy, e.g. "Free cancellation up until 1 hour before pickup".')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fleet/')),
                ('passenger_capacity', models.PositiveSmallIntegerField(default=0)),
                ('luggage_capacity', models.PositiveSmallIntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Rate per hour for hourly hire.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('meet_greet_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Airport meet-and-greet supplement.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fare floor. Applied after every other adjustment.', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate rather than delete: bookings reference this row.')),
                ('legacy_car_id', models.IntegerField(blank=True, db_index=True, help_text='`limousin_car_list.id`, for idempotent imports.', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DistanceBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_miles', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lower bound, inclusive.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('to_miles', models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound, exclusive. Leave empty for the final, unbounded band.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('rate_per_mile', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['vehicle', 'from_miles'],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'from_miles'), name='unique_band_start_per_vehicle')],
            },
        ),
    ]
