# Generated by Django 5.2.17 on 2026-08-12 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('nature', models.CharField(choices=[('general', 'General enquiry'), ('service', 'Service enquiry'), ('corporate', 'Corporate account')], db_index=True, default='general', max_length=30)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('company_name', models.CharField(blank=True, help_text='Corporate enquiries only.', max_length=255)),
                ('source_ip', models.GenericIPAddressField(blank=True, help_text='Legacy `clint_ip` (sic), stored as free text.', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply_body', models.TextField(blank=True)),
                ('legacy_table', models.CharField(blank=True, help_text='Which legacy table this came from.', max_length=40)),
                ('legacy_row_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries_replied', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', '-created_at'], name='enquiries_c_is_read_fbdedf_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('legacy_row_id__isnull', False)), fields=('legacy_table', 'legacy_row_id'), name='unique_legacy_enquiry')],
            },
        ),
    ]
