# Generated by Django 5.2.17 on 2026-08-12 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactmessage',
            name='unique_legacy_enquiry',
        ),
        migrations.AddConstraint(
            model_name='contactmessage',
            constraint=models.UniqueConstraint(fields=('legacy_table', 'legacy_row_id'), name='unique_legacy_enquiry'),
        ),
    ]
