# Generated by Django 5.2.17 on 2026-08-12 17:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('legacy', 'Legacy (pre-migration)')], default='stripe', max_length=12)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, help_text='Stripe PaymentIntent. Empty for imported historical records, which predate this integration.', max_length=64)),
                ('charge_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Awaiting payment method'), ('requires_action', 'Requires customer action (3-D Secure)'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown (historical record)')], db_index=True, default='requires_payment_method', max_length=24)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, help_text='Last four digits only — never the full number.', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{0,4}$', 'Last four digits only.')])),
                ('receipt_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('legacy_orderdetail_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='PROTECT: financial records are never cascade-deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_refund_id', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Which staff member issued it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_issued', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('card_last4', ''), ('card_last4__regex', '^\\d{4}$'), _connector='OR'), name='card_last4_is_four_digits_or_blank'),
        ),
    ]
