# Generated by Django 5.2.17 on 2026-08-13 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('test', 'Test mode'), ('live', 'Live mode')], default='test', help_text='Live mode charges real cards.', max_length=4)),
                ('publishable_key', models.CharField(blank=True, help_text='Safe to expose — this is sent to the browser.', max_length=255)),
                ('_secret_key', models.TextField(blank=True, db_column='secret_key_encrypted', help_text='Encrypted at rest.', verbose_name='secret key')),
                ('_webhook_secret', models.TextField(blank=True, db_column='webhook_secret_encrypted', help_text='Encrypted at rest.', verbose_name='webhook signing secret')),
                ('statement_descriptor', models.CharField(blank=True, help_text="What appears on the customer's card statement (max 22 chars).", max_length=22)),
                ('is_enabled', models.BooleanField(default=False, help_text='Turn off to stop taking card payments without deleting the keys.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment settings',
                'verbose_name_plural': 'payment settings',
            },
        ),
    ]
