# Generated by Django 5.2.17 on 2026-08-13 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_webhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', help_text='Live mode takes real payments.', max_length=8)),
                ('client_id', models.CharField(blank=True, help_text='From the PayPal app. Public — it is sent to the browser.', max_length=255)),
                ('_client_secret', models.TextField(blank=True, db_column='client_secret_encrypted', help_text='Encrypted at rest.', verbose_name='client secret')),
                ('webhook_id', models.CharField(blank=True, help_text='From the PayPal webhook you create. Required to verify incoming events.', max_length=64)),
                ('brand_name', models.CharField(blank=True, help_text='Shown on the PayPal checkout page.', max_length=127)),
                ('is_enabled', models.BooleanField(default=False, help_text='Turn off to hide PayPal at checkout without deleting the credentials.')),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(blank=True, null=True)),
                ('last_test_error', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PayPal settings',
                'verbose_name_plural': 'PayPal settings',
            },
        ),
    ]
