# Generated by Django 5.2.17 on 2026-09-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paypalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash (pay the driver)'), ('legacy', 'Legacy (pre-migration)')], default='stripe', max_length=12),
        ),
    ]
