# Generated by Django 5.2.17 on 2026-10-06 13:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guest_email_booking_guest_phone'),
        ('payments', '0005_alter_payment_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='PROTECT: financial records are never cascade-deleted. Null for an off-session charge not tied to a booking (e.g. a trip extension).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking'),
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=64, unique=True)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('last4', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Exactly four digits.')])),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
