"""Bookings admin. Day-to-day dispatch work lives in the dashboard (Phase 5)."""

from django.contrib import admin
from django.utils.html import format_html

from payments.models import Payment

from .models import Booking, BookingPriceLine, BookingStatusChange, Driver


class BookingPriceLineInline(admin.TabularInline):
    model = BookingPriceLine
    extra = 0
    fields = ["kind", "label", "amount", "ordering"]
    readonly_fields = ["kind", "label", "amount", "ordering"]
    can_delete = False
    verbose_name_plural = "Fare breakdown (generated by the pricing engine)"

    def has_add_permission(self, request, obj=None):
        return False


class BookingStatusChangeInline(admin.TabularInline):
    model = BookingStatusChange
    extra = 0
    fields = ["changed_at", "from_status", "to_status", "changed_by", "note"]
    readonly_fields = fields
    can_delete = False
    ordering = ["-changed_at"]

    def has_add_permission(self, request, obj=None):
        return False


class PaymentInline(admin.TabularInline):
    model = Payment
    extra = 0
    fields = ["provider", "status", "amount", "currency", "masked_card", "created_at"]
    readonly_fields = fields
    can_delete = False

    def has_add_permission(self, request, obj=None):
        return False

    @admin.display(description="Card")
    def masked_card(self, obj):
        return obj.masked_card or "—"


@admin.register(Booking)
class BookingAdmin(admin.ModelAdmin):
    list_display = [
        "reference", "pickup_at", "status_badge", "customer_name",
        "vehicle_name_snapshot", "route", "driver", "total",
    ]
    list_filter = ["status", "trip_type", "vehicle", "pickup_at"]
    search_fields = [
        "reference", "pickup_address", "dropoff_address", "pickup_sign",
        "flight_number", "customer__email", "customer__first_name",
        "customer__last_name", "legacy_order_id",
    ]
    date_hierarchy = "pickup_at"
    autocomplete_fields = ["customer", "driver", "vehicle"]
    inlines = [BookingPriceLineInline, PaymentInline, BookingStatusChangeInline]
    readonly_fields = [
        "reference", "legacy_order_id", "created_at", "updated_at",
        "vehicle_name_snapshot", "subtotal", "surcharge_total", "tax", "total",
    ]

    fieldsets = (
        (None, {"fields": ("reference", "status", "trip_type")}),
        ("Itinerary", {
            "fields": (
                "pickup_at", "pickup_address", "dropoff_address",
                "distance_miles", "duration_minutes", "hours",
            ),
        }),
        ("Party", {"fields": ("customer", "passenger_count", "luggage_count")}),
        ("Vehicle & driver", {"fields": ("vehicle", "vehicle_name_snapshot", "driver")}),
        ("Airport", {"fields": ("flight_number", "pickup_sign", "meet_and_greet")}),
        ("Fare", {
            "fields": ("subtotal", "surcharge_total", "tax", "total", "currency"),
            "description": "Computed by the pricing engine. See the breakdown below.",
        }),
        ("Cancellation", {
            "fields": ("cancelled_at", "cancellation_reason", "cancellation_fee"),
            "classes": ("collapse",),
        }),
        ("Notes", {"fields": ("notes",)}),
        ("Legacy", {"fields": ("legacy_order_id",), "classes": ("collapse",)}),
        ("Timestamps", {"fields": ("created_at", "updated_at"), "classes": ("collapse",)}),
    )

    def get_queryset(self, request):
        return super().get_queryset(request).select_related(
            "vehicle", "driver", "customer",
        )

    @admin.display(description="Status", ordering="status")
    def status_badge(self, obj):
        colours = {
            Booking.Status.PENDING: "#8a6320",
            Booking.Status.CONFIRMED: "#1f4e8c",
            Booking.Status.COMPLETED: "#1e6b41",
            Booking.Status.CANCELLED: "#8a3a34",
        }
        return format_html(
            '<span style="color:{};font-weight:600">{}</span>',
            colours.get(obj.status, "#333"), obj.get_status_display(),
        )

    @admin.display(description="Route")
    def route(self, obj):
        if obj.trip_type == Booking.TripType.HOURLY:
            return f"{obj.hours or 0:g} h hire"
        pickup = (obj.pickup_address or "—")[:28]
        dropoff = (obj.dropoff_address or "—")[:28]
        return format_html("{} → {}", pickup, dropoff)

    @admin.display(description="Customer")
    def customer_name(self, obj):
        return obj.customer_name


@admin.register(Driver)
class DriverAdmin(admin.ModelAdmin):
    list_display = ["full_name", "phone", "email", "is_active", "booking_count"]
    list_filter = ["is_active"]
    search_fields = ["full_name", "phone", "email"]

    @admin.display(description="Bookings")
    def booking_count(self, obj):
        return obj.bookings.count()
