/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/pages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List published pages
         * @description Every published page. Use this to build navigation and a sitemap.
         */
        get: operations["pages_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pages/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one published page
         * @description Content and SEO metadata for a CMS page. Unpublished pages 404.
         */
        get: operations["pages_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List bookable vehicles
         * @description Active vehicles only. Per-mile rates are not exposed — fares come from the quote endpoint so they cannot be recomputed (or disputed) client-side.
         */
        get: operations["vehicles_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/availability/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Surcharge windows and blackout dates
         * @description For the date picker, so a customer can see before choosing that a late-night pickup or an event date costs more.
         */
        get: operations["availability_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quotes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Price a journey across every vehicle
         * @description Measures the journey server-side from the two addresses and returns a fare per bookable vehicle.
         *
         *     **There is no `distance_miles` field and no price field.** A client cannot declare either. Each result carries a signed `quote_token` — present it to `POST /api/bookings/` and the fare is recomputed before anything is stored.
         *
         *     Supply `dropoff_address` for a transfer, or `hours` for hourly hire, never both. Throttled to 30/hour.
         */
        post: operations["quotes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a booking from a signed quote
         * @description Redeems a `quote_token` and creates a booking in `pending` status. The fare is recomputed from the token; any amount in the request body is ignored because no such field exists.
         *
         *     Sign in first, or supply `guest_email` for guest checkout. Take payment next via `POST /api/payments/intent/`.
         */
        post: operations["bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/bookings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in customer's bookings */
        get: operations["account_bookings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/bookings/{reference}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read or cancel one of your bookings
         * @description Scoped to the signed-in customer. Another customer's reference returns **404, not 403** — a 403 would confirm the reference exists and allow bookings to be enumerated.
         *
         *     `PATCH {"action": "cancel"}` cancels, if the pickup is still in the future.
         */
        get: operations["account_bookings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Read or cancel one of your bookings
         * @description Scoped to the signed-in customer. Another customer's reference returns **404, not 403** — a 403 would confirm the reference exists and allow bookings to be enumerated.
         *
         *     `PATCH {"action": "cancel"}` cancels, if the pickup is still in the future.
         */
        patch: operations["account_bookings_partial_update"];
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Sets a session cookie. A wrong password and an unknown address return the identical response, so this cannot be used to discover who has an account.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Password strength is enforced. Registering an address that already exists returns **202 with a neutral message** rather than an error, for the same anti-enumeration reason as sign-in.
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a password reset link
         * @description Always returns 202, whether or not the address is registered.
         *
         *     The reset is completed on Django-served pages under `/accounts/`, not in the frontend. Note that customers migrated from the previous system have no password at all until they use this.
         */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in customer */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/config/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Publishable key and payment availability
         * @description What the browser needs to render Stripe Elements. Only the publishable key is ever exposed; it is designed to be public.
         */
        get: operations["payments_config_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/intent/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start payment for a booking
         * @description Creates a Stripe PaymentIntent and returns its client secret for Stripe Elements.
         *
         *     The amount comes from the booking, which the pricing engine computed. Nothing in the request body influences it.
         *
         *     **Confirmation happens by webhook, not here.** A successful card confirmation in the browser does not mark the booking paid — Stripe calls `/api/payments/webhook/` and that is what confirms it. Poll `/api/account/bookings/{reference}/` or show a pending state.
         */
        post: operations["payments_intent_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/webhook/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe webhook (not for frontend use)
         * @description Called by Stripe, never by the frontend. Requests are authenticated by HMAC signature over the raw body; unsigned requests are refused.
         *
         *     Idempotent: every processed event id is recorded, so Stripe's retries cannot double-confirm a booking or double-record a refund.
         */
        post: operations["payments_webhook_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enquiries/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit the contact form
         * @description Throttled to 10/hour per address.
         */
        post: operations["enquiries_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `cancel` - cancel
         * @enum {string}
         */
        ActionEnum: "cancel";
        /** @description Everything a date picker needs to warn about surcharged times. */
        Availability: {
            blackout_dates: components["schemas"]["BlackoutDate"][];
            time_surcharges: components["schemas"]["TimeSurcharge"][];
        };
        BlackoutDate: {
            /** Format: date */
            date: string;
            name: string;
            percentage: string;
        };
        Booking: {
            /** @description Customer-facing booking code. */
            readonly reference: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly status_display: string;
            readonly trip_type: components["schemas"]["TripTypeEnum"];
            readonly pickup_address: string;
            readonly dropoff_address: string;
            /** Format: date-time */
            readonly pickup_at: string;
            /**
             * Format: decimal
             * @description From the Distance Matrix API. Null for hourly hire.
             */
            readonly distance_miles: string | null;
            readonly duration_minutes: number | null;
            /**
             * Format: decimal
             * @description Booked hours, for hourly hire.
             */
            readonly hours: string | null;
            readonly passenger_count: number;
            readonly luggage_count: number;
            readonly flight_number: string;
            /** @description Name shown on the placard. */
            readonly pickup_sign: string;
            readonly meet_and_greet: boolean;
            /** @description Customer instructions. */
            readonly notes: string;
            readonly vehicle_name: string;
            /** Format: decimal */
            readonly subtotal: string;
            /** Format: decimal */
            readonly surcharge_total: string;
            /** Format: decimal */
            readonly tax: string;
            /** Format: decimal */
            readonly total: string;
            readonly currency: string;
            readonly price_lines: {
                [key: string]: unknown;
            }[];
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description Create a booking from a signed quote token.
         *
         *     Deliberately has no `total`, `subtotal` or any other money field: the server
         *     recomputes the fare from the token. A client-supplied amount is not merely
         *     ignored here, it is impossible to express.
         */
        BookingCreateRequest: {
            quote_token: string;
            /** @default 1 */
            passenger_count: number;
            /** @default 0 */
            luggage_count: number;
            flight_number?: string;
            pickup_sign?: string;
            notes?: string;
            guest_email?: string;
            guest_name?: string;
        };
        /** @description A human-readable message. Used for errors and simple acknowledgements. */
        Detail: {
            detail: string;
        };
        EnquiryRequest: {
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            nature?: components["schemas"]["NatureEnum"];
            subject?: string;
            message: string;
            /** @description Corporate enquiries only. */
            company_name?: string;
        };
        /** @description The route as measured server-side. Null for hourly hire. */
        Journey: {
            /** @description Decimal string, e.g. "25.000". */
            distance_miles: string;
            duration_minutes: number;
            /** @description As resolved by the mapping service. */
            pickup_address: string;
            dropoff_address: string;
        };
        /**
         * @description * `base` - base
         *     * `band` - band
         *     * `surcharge` - surcharge
         *     * `meet_greet` - meet_greet
         *     * `minimum_adjustment` - minimum_adjustment
         *     * `tax` - tax
         * @enum {string}
         */
        KindEnum: "base" | "band" | "surcharge" | "meet_greet" | "minimum_adjustment" | "tax";
        LoginRequestRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description * `general` - General enquiry
         *     * `service` - Service enquiry
         *     * `corporate` - Corporate account
         * @enum {string}
         */
        NatureEnum: "general" | "service" | "corporate";
        Page: {
            /** @description URL path. Changing this breaks search rankings — don't. */
            slug: string;
            readonly url: string;
            title: string;
            page_type?: components["schemas"]["PageTypeEnum"];
            body?: string;
            meta_title?: string;
            meta_description?: string;
            meta_keywords?: string;
        };
        /**
         * @description * `home` - Homepage
         *     * `service` - Service landing page
         *     * `standard` - Standard content page
         *     * `legal` - Legal / policy page
         * @enum {string}
         */
        PageTypeEnum: "home" | "service" | "standard" | "legal";
        PasswordResetRequestRequest: {
            /** Format: email */
            email: string;
        };
        PatchedCancelBookingRequest: {
            action?: components["schemas"]["ActionEnum"];
        };
        PaymentConfig: {
            enabled: boolean;
            /** @description Safe to embed in the page. Empty when disabled. */
            publishable_key: string;
            /** @description "test" or "live". */
            mode: string | null;
        };
        PaymentIntentRequestRequest: {
            /** @description Booking reference. */
            reference: string;
        };
        PaymentIntentResponse: {
            /** @description Pass to Stripe Elements. */
            client_secret: string;
            publishable_key: string;
            amount: string;
            currency: string;
            reference: string;
        };
        /** @description One component of a fare. */
        QuoteLine: {
            kind: components["schemas"]["KindEnum"];
            /** @description e.g. "19 mi in 6–50 mi × $2.90". */
            label: string;
            /** @description Decimal string. Money is never a float. */
            amount: string;
        };
        /**
         * @description A request for fares.
         *
         *     Deliberately accepts NO distance and NO price. A transfer is described by
         *     its two addresses and the server measures it (pricing/distance.py); an
         *     hourly hire is described by its duration. A client-supplied distance is a
         *     client-supplied fare with extra steps.
         */
        QuoteRequestRequest: {
            pickup_address: string;
            dropoff_address?: string;
            /** Format: date-time */
            pickup_at: string;
            /**
             * Format: decimal
             * @description Hourly hire only. Omit for a point-to-point transfer.
             */
            hours?: string | null;
            /** @default false */
            meet_and_greet: boolean;
        };
        QuoteResponse: {
            journey: components["schemas"]["Journey"] | null;
            quotes: components["schemas"]["QuoteResult"][];
        };
        /** @description A priced option for one vehicle. */
        QuoteResult: {
            vehicle_id: number;
            vehicle_name: string;
            subtotal: string;
            surcharge_total: string;
            tax: string;
            total: string;
            currency: string;
            lines: components["schemas"]["QuoteLine"][];
            /** @description Signed and short-lived. Present this to create a booking; the server recomputes the fare from it. */
            quote_token: string;
        };
        RegisterRequestRequest: {
            /** Format: email */
            email: string;
            password: string;
            first_name?: string;
            last_name?: string;
            phone?: string;
        };
        /**
         * @description * `pending` - Pending payment
         *     * `confirmed` - Confirmed
         *     * `completed` - Completed
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        StatusEnum: "pending" | "confirmed" | "completed" | "cancelled";
        TimeSurcharge: {
            name: string;
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
            percentage: string;
            crosses_midnight: boolean;
        };
        /**
         * @description * `transfer` - Point-to-point transfer
         *     * `hourly` - Hourly hire
         * @enum {string}
         */
        TripTypeEnum: "transfer" | "hourly";
        User: {
            /** Format: email */
            email: string;
            first_name: string;
            last_name: string;
            phone?: string;
        };
        Vehicle: {
            readonly id: number;
            /** @description e.g. "Business Class". */
            name: string;
            slug: string;
            description?: string;
            /** @description Marketing copy, e.g. "Free cancellation up until 1 hour before pickup". */
            features?: string;
            passenger_capacity?: number;
            luggage_capacity?: number;
            /**
             * Format: decimal
             * @description Fare floor. Applied after every other adjustment.
             */
            minimum_fare?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    pages_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"][];
                };
            };
        };
    };
    pages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description URL slug, e.g. "fleet". */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    vehicles_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"][];
                };
            };
        };
    };
    availability_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
        };
    };
    quotes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["QuoteRequestRequest"];
                "multipart/form-data": components["schemas"]["QuoteRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BookingCreateRequest"];
                "multipart/form-data": components["schemas"]["BookingCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    account_bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    account_bookings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    account_bookings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCancelBookingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCancelBookingRequest"];
                "multipart/form-data": components["schemas"]["PatchedCancelBookingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequestRequest"];
                "multipart/form-data": components["schemas"]["LoginRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequestRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequestRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    payments_config_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentConfig"];
                };
            };
        };
    };
    payments_intent_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentIntentRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PaymentIntentRequestRequest"];
                "multipart/form-data": components["schemas"]["PaymentIntentRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentIntentResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Already paid, or the booking was cancelled. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            /** @description Card payments are not configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    payments_webhook_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    enquiries_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnquiryRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["EnquiryRequest"];
                "multipart/form-data": components["schemas"]["EnquiryRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
}
